# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: self-hosted-demo-eks

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install '
  
- script: |
    npm run build
  displayName: 'npm build '
- task: CopyFiles@2
  inputs:
    Contents: '**/k8s/deploy.yaml'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'simple-react-app'
    publishLocation: 'Container'
  
- task: Docker@2
  inputs:
    containerRegistry: 'docker connection'
    repository: 'sachinl18/react-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'